// app/layout.tsx หรือ root layout ที่ใช้ใน Next.js App Router
import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import { ComponentsNavbar } from "@/app/components/ComponentsNavbar";
import { ComponentsFooter } from "@/app/components/ComponentsFooter";

// ✅ ใช้ฟอนต์ Prompt ที่รองรับภาษาไทย
const prompt = Prompt({
  weight: ["400", "700"],
  subsets: ["latin", "thai"],
  variable: "--font-prompt",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" data-theme="emerald">
      <body className={`${prompt.variable} font-sans antialiased`}>
        <ComponentsNavbar />
        {children}
        <ComponentsFooter />
      </body>
    </html>
  );
}
